import React, { useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import './LandingPage.css';

export default function LandingPage() {
  const navigate = useNavigate();
  const heroRef = useRef(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(el => el.target.classList.add('visible'));
      },
      { threshold: 0.1 }
    );
    document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  return (
    <div className="landing">
      {/* Background texture */}
      <div className="landing-bg">
        <div className="bg-grid" />
        <div className="bg-glow bg-glow-1" />
        <div className="bg-glow bg-glow-2" />
      </div>

      {/* Header */}
      <header className="landing-header">
        <div className="header-logo">
          <span className="logo-badge">LEAP</span>
          <span className="logo-text">Academy</span>
        </div>
        <div className="header-trust">
          <span>⭐⭐⭐⭐⭐</span>
          <span>120,000+ professionals transformed</span>
        </div>
      </header>

      {/* Hero */}
      <section className="landing-hero" ref={heroRef}>
        <div className="container">
          <div className="hero-eyebrow reveal">
            <span className="eyebrow-pill">Free 3-Minute Assessment</span>
          </div>

          <h1 className="hero-title reveal">
            What's Your
            <em className="title-accent"> Executive<br />Edge Score?</em>
          </h1>

          <p className="hero-subtitle reveal">
            Discover the hidden gap between where you are and where you should be —
            and get a personalised blueprint to close it.
          </p>

          <div className="hero-stats reveal">
            <div className="stat">
              <span className="stat-number">$80M+</span>
              <span className="stat-label">Generated by clients</span>
            </div>
            <div className="stat-divider" />
            <div className="stat">
              <span className="stat-number">120K+</span>
              <span className="stat-label">Professionals coached</span>
            </div>
            <div className="stat-divider" />
            <div className="stat">
              <span className="stat-number">5</span>
              <span className="stat-label">Continents reached</span>
            </div>
          </div>

          <button
            className="cta-primary reveal"
            onClick={() => navigate('/quiz')}
          >
            <span>Discover Your Score</span>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M5 12h14M12 5l7 7-7 7"/>
            </svg>
          </button>

          <p className="hero-note reveal">
            Takes 3 minutes · 100% personalised results · Used by leaders at Google, JPMorgan & McKinsey
          </p>
        </div>
      </section>

      {/* Social proof strip */}
      <section className="proof-strip reveal">
        <div className="container-wide">
          <div className="proof-logos">
            {['Forbes', 'Yahoo Finance', 'NBC', 'Fox', 'MarketWatch', 'ABC'].map(logo => (
              <span key={logo} className="proof-logo">{logo}</span>
            ))}
          </div>
        </div>
      </section>

      {/* What you'll discover */}
      <section className="landing-features">
        <div className="container">
          <h2 className="features-title reveal">What Your Score Reveals</h2>

          <div className="features-grid">
            {[
              {
                icon: '🎯',
                title: 'Your Executive Edge Score',
                desc: 'A precise composite score across Brand Power, Confidence, Leadership Presence, and Opportunity Radar.'
              },
              {
                icon: '📋',
                title: 'Your Personalised Action Plan',
                desc: '3 specific, high-impact moves tailored to your exact answers, income level, and career goals.'
              },
              {
                icon: '✉️',
                title: 'A Letter From Ilana',
                desc: 'Personalised consulting based on your quiz answers — the advice she gives clients in $5,000 sessions.'
              },
              {
                icon: '🎓',
                title: 'Free Training Access',
                desc: 'Curated video training matched to your result tier — the exact content that has transformed thousands of careers.'
              },
            ].map((feature, i) => (
              <div key={i} className="feature-card reveal" style={{ animationDelay: `${i * 0.1}s` }}>
                <span className="feature-icon">{feature.icon}</span>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-desc">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonial preview */}
      <section className="landing-testimonials">
        <div className="container">
          <h2 className="reveal" style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(1.5rem, 3vw, 2rem)', marginBottom: '2rem', textAlign: 'center' }}>
            Professionals Like You Have Already Leaped
          </h2>
          <div className="testimonials-grid">
            {[
              {
                quote: "Within 3 months it changed how I showed up at work. I allowed myself to be more comfortable with who I am — and got promoted to VP.",
                name: "Sarah K.",
                role: "VP Engineering, Series C Startup"
              },
              {
                quote: "Leap helped me land two executive offers simultaneously and negotiate a $140K salary jump. I never thought this was possible for me.",
                name: "Marcus T.",
                role: "Director, JPMorgan"
              },
              {
                quote: "I joined Ilana's program and within 6 months I was a founder, board member, and angel investor. It literally changed my life.",
                name: "Priya M.",
                role: "Founder & Board Director"
              },
            ].map((t, i) => (
              <div key={i} className="testimonial-card reveal" style={{ animationDelay: `${i * 0.1}s` }}>
                <div className="testimonial-stars">⭐⭐⭐⭐⭐</div>
                <p className="testimonial-quote">"{t.quote}"</p>
                <div className="testimonial-author">
                  <span className="author-name">{t.name}</span>
                  <span className="author-role">{t.role}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="landing-final-cta">
        <div className="container">
          <div className="final-cta-card reveal">
            <h2>Ready to Discover Your Executive Edge Score?</h2>
            <p>3 minutes. Fully personalised. The most valuable assessment you'll take this year.</p>
            <button className="cta-primary" onClick={() => navigate('/quiz')}>
              <span>Start Your Free Assessment</span>
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <path d="M5 12h14M12 5l7 7-7 7"/>
              </svg>
            </button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="container">
          <p>© 2025 Leap Academy · <a href="https://www.leapacademy.com" target="_blank" rel="noopener noreferrer">leapacademy.com</a></p>
        </div>
      </footer>
    </div>
  );
}
